name: example
description: An example.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web_browser:
    path: ..

dev_dependencies:
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
