name: web_browser
version: 0.6.1
description:
  A cross-platform Flutter widget for displaying websites and other web content. Has navigation
  Cupertino/Material buttons and takes care of complex platform differences.
homepage: https://github.com/dint-dev/web_browser

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  #
  # Packages by Google:
  #
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.6
  webview_flutter_android: ^3.4.2
  webview_flutter_web: ^0.2.2+1
  webview_flutter_wkwebview: ^3.2.1

  #
  # Packages by other parties:
  #
  share_plus: ^6.3.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter