name: web_browser
version: 0.5.0
description:
  A cross-platform Flutter widget for displaying websites and other web content. Has optional
  navigation buttons.
homepage: https://github.com/dint-dev/web_browser

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  csp: ^0.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  meta: ^1.3.0
  share: ^2.0.0
  universal_html: ^2.0.0
  web_node: ^0.2.0
  webview_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0